### ISSUE TITLE
Thumbs proportional to window (?)

### ISSUE THREAD

**Issue by waxfingers** [occivink/mpv-gallery-view#1]
Firts let me say this is such a cool script =)

I have increased the thumbs' size a bit for a clearer view when in full screen on a big display, the thing is when I start mpv in "windowed" (normal) mode the thumbs are too big; is there a way the thumbs could scale up or down with the window, not dissimilar to the osd-scale?

Thanks

**Comment by occivink** [comment]
Thanks for the compliment.

The reason why the size of the thumbnails is fixed is that we must generate them exactly at the size we want to display them, as mpv doesn't do any scaling of "overlays". While we could make them proportional to the size of the window (say, 10%), we would have to generate a *lot* of thumbnail files to accommodate for that, and I think that would look pretty bad, especially during the resize.

However, one thing that could do is have only a few predefined thumbnail sizes and then switch to one of them depending on the size of the window. 
The way I would see this working is that the script should expose a "reconfigure" command, that you then call from another lua script like so:
```
local presets = {
   720*480   = { 160, 90 },
   1280*720  = { 192, 108 },
   1920*1080 = { 224, 126 },
   2560*1440 = { 256, 144 },
}
local current_size = {}

function change_thumbnail_preset()
    local w, h = mp.get_osd_size()
    local size = w * h
    local changed = false
    for window_size, thumbnail_size in ipairs(presets) do
        if size < window_size then
            if thumbnail_size ~= current_size then
                current_size = thumbnail_size
                changed = true
            end
            break
        end
    end
    if changed then
        mp.commandv("script-message-to", "gallery", "reconfigure", current_size[1], current_size[2])
    end
end

mp.observe_property("osd-width", "native", change_thumbnail_preset)
mp.observe_property("osd-height", "native", change_thumbnail_preset)
```

The reason it would have to be done in a script is that I can't see a simple way to expose this in the configuration.

**Comment by waxfingers** [comment]
> mpv doesn't do any scaling of "overlays"

OK, good to know

> we would have to generate a lot of thumbnail files to accommodate for that, and I think that would look pretty bad, especially during the resize

Too many thumbnails and no compost =)

This is an "issue" I also have with the [thumbnails generator](https://github.com/TheAMM/mpv_thumbnail_script), the thumbs are either too big in windowed mode or too small at fullscreen.
- - - 
&nbsp;  
I know nuthin' about coding but I think I understand the limitations and your idea for presets depending on screen size, nice. I imagine it implemented like (if not mistaken wm4) autoprofiles... but with window size. Something like:

- I open a video; differently from autoprofiles, doesn't matter its size.

- I make mpv fullscreen, then stroke `g` which would tell gallery script window is 2560*1440 so it would generate 256 by 144 px thumbs.

- If in windowed mode, script would generate smaller thumbs.

A couple things come to mind, one is that would be good if user could change presets' sizes, maybe that's a given. What would happen (my own situation)
 having `window-scale = 0.5` and `autofit-smaller = 1920` on mpv's conf?
  
- - -   
&nbsp;   
Another mushroom 🍄 poped in head-swamp, a mode for big screens that activates when mpv is playing fullscreen and uses the 64 thumbs' limitation to create the thumbnails' size accordingly... now that I said it aloud, maybe this is the most useful way (to my ego's belly at least), but I bet a PITA to implement. Anyway, I leave it here:  
the script would need to "know" window size and how many elements it had to display, then it would adjust thumbs' size so thumbs would populate the whole screen; when more than 64, number of elements would be set to 64. I know, this doesn't resize the thumbs as I asked but seems (theoretically) useful, especially when browsing stills.  

All good garbage :P

**Comment by occivink** [comment]
>I know nuthin' about coding but I think I understand the limitations and your idea for presets depending on screen size, nice.

Oh it's not about screen size, what I proposed was regarding window size. So when you resize the window dynamically, the thumbnails would switch to one preset or another.
So in my example:
window smaller than 720x480 => thumbs are 160x90
window smaller than 1280x720 => thumbs are 192x108 
and so on.  
Of course the thumbnails would have to be generated for each size, but I think that would be acceptable. Anyway I'll implement that and you can tell me if you're happy with it.

**Comment by waxfingers** [comment]
... yeah I meant window size (lapsus cley)
SUPER!!!

**Comment by occivink** [comment]
Ok it's done. You can find the new option [here](https://github.com/occivink/mpv-gallery-view/blob/master/lua-settings/gallery.conf#L18-L33), hopefully it's understandable.

**Comment by waxfingers** [comment]
Sorry to reopen the issue, just now saw that you'd reply 🙈
Maybe I'm doing something wrong but it is not working for me. 
I have  `dynamic_thumbnail_size=3686400,768,432;691200,192,108` but no matter if SD, HD or 4K the thumbs are always small. ???

macos 10.13.3
mpv 0.28.0

**Comment by occivink** [comment]
>Okay, it is not as straightforward as it seems

Yes it's not exactly simple to make such an option configurable, and I'm not entirely satisfied with the solution.

I can't reproduce your bug, and the code *should* handle fullscreening and resizing, whether the gallery is already started or not. Could you post some simple reprodution steps?

**Comment by waxfingers** [comment]
I disabled everything in mpv's conf and input files, just left the osc=no. My displays settings

![screen](https://user-images.githubusercontent.com/13238340/36630484-ec773ce4-195e-11e8-9d82-c9a54833d616.jpg)

Now, before going to gallery conf settings (which admittedly I could have set up wrongly), the resize of **the window behaviour happens no matter the conf (set it to deffault)**; my gallery settings `thumbnail_width=768, thumbnail_height=432` and `dynamic_thumbnail_size=2073600,288,162`

- - - - 
To reproduce both "bugs"

1. open a folder with images  
2. resize to anything smaller than FHD (1080p)  
3. start the galley script, wow such a nice array of little image siblings, _no-iron-realy-cool_  
4. exit gallery mode <--- it returns to first state of mpv's window when images were opened and NOT the resized window; non standard behaviour
5. resize the window to anything bigger than FHD, fullscreen is perfect.
6. enter gallery mode <--- expected to render new (bigger = 768, 432) thumbs, instead "reuses" the ones from dynamic_thumbnail.

As I mentioned above, if done the other way around, settings are respected; and settings want respect  :P

**Comment by occivink** [comment]
Ah I see, it's *just* a misunderstanding of how the option work. Basically, when `dynamic_thumbnail_size` is defined, `thumbnail_width` and `thumbnail_height` are not considered at all anymore (which wasn't the case until now, but that was a bug).

In your case I can see that you want two thumbnail sizes: 
* 288x162 when the window is FHD (= 1920x1080 = 2073600 pixels) or smaller
* 768x432 when it's bigger than that

To do that, we must set `dynamic_thumbnail_size` to `2073600,288,162  ;  1e20,768,423`. If we decompose it, it works like this:
* `2073600,288,162`: is the window smaller than 2073600 pixels? if yes, the thumbnails are now 288x162. if not, the next preset is considered
* `1e20,768,423`: is the window smaller than 1e20 (= 10^20)? if yes, the thumbnails are now 768x423.

Note that you could add more than just two presets: in the lua-settings.conf I linked, you can see examples with 3 and 4 presets.

**Comment by waxfingers** [comment]
That's why I lamented like a soulless snail _not as straightforward as it seems_ now with your kind explanation it is clear 🐌 >> 🏎

Your example **also works perfectly** regarding thumbs... still the other "issue" of the resizing of the window... which is something I can happily live with. So now a **thankyou** occivink is in order

**Comment by occivink** [comment]
Agreed, in general I think mpv's window size handling is annoying. I'll add an option for that

**Comment by waxfingers** [comment]
It seems to be some issue for gallery to **load thumbs when is a video downloaded from web but ONLY in fullscreen**. sample 387KB

[sample_FS_thumbs_iddu.zip](https://github.com/occivink/mpv-gallery-view/files/1777621/sample_FS_thumbs_iddu.zip)

**Comment by occivink** [comment]
Do you have some more detailed reproduction steps? This sample seems to work well here. 
Also can you tell me what value you use for `take_thumbnail_at=` in `gallery.conf`? I recently changed the syntax for this option and it may be causing issues.

**Comment by waxfingers** [comment]
- Open sample video (downloaded from YT)
- make mpv fullscreen
- gallery thumbs is black (none)

Expected behaviour is same as with any other image or video: a thumb per video, in my case, of 768 by 432 pixels size. This does not happen on windowed mode, with other videos nor with dynamic_thumbnail disabled.


`# static thumbnail size  
thumbnail_width=768  
thumbnail_height=432`

`dynamic_thumbnail_size=2073600,288,162 ; 1e20,768,423`

**Comment by waxfingers** [comment]
Just to leave a note: the sub-issue mentioned here - https://github.com/occivink/mpv-gallery-view/issues/1#issuecomment-370157965 no longer is true; also main "issue", *Thumbs proportional to window* was addressed and is working flawlessly 👌
Thanks
