### ISSUE TITLE
playback starts when leaving menu

### ISSUE THREAD

**Issue by Soundtoxin** [occivink/mpv-gallery-view#11]
After I press esc (or the key that brought up the menu such as `c` or `g`) from the contacts or playlist view, the file starts playing if paused. I have on autopause and am testing the scripts on a file I'm not ready to watch. Is this a bug?

**Comment by occivink** [comment]
No, but it's something [you can configure](https://github.com/occivink/mpv-gallery-view/blob/master/script-opts/playlist_view.conf#L52-L53) :)
