### ISSUE TITLE
problem with  thumbnails

### ISSUE THREAD

**Issue by gareaugorille** [occivink/mpv-gallery-view#12]
Hi, 

I have followed the installation instructions but I must be doing something wrong: pressing g, the script correctly opens the playlist panel, but it does not generate thumbnails (though the thumbnail directory exists, thumbnail spaces are therefore empty), although moving the cursor to a different, empty thumbnail space correctly opens a different file. When loading the playlist, mpv returns the following error messages:

> [gallery_thumbgen]
> [gallery_thumbgen] stack traceback:
> [gallery_thumbgen] 	.../.config/mpv/scripts/gallery-thumbgen.lua:6: in main chunk
> [gallery_thumbgen] 	[C]: ?
> [gallery_thumbgen] 	[C]: ?
> [gallery_thumbgen] Lua error: .../.config/mpv/scripts/gallery-thumbgen.lua:6: attempt to call field 'getpid' (a nil value)

Am I missing something? Thanks!

**Comment by occivink** [comment]
This looks like certain lua functions are missing, are you using the latest mpv version? Check with `mpv -v`, latest should be 0.29.

**Comment by gareaugorille** [comment]
thanks: yes, that was the problem. I have updated mpv, and it now works flawlessly.
