### ISSUE TITLE
Cannot Find main.*

### ISSUE THREAD

**Issue by Vortexakhaj** [occivink/mpv-gallery-view#21]
![Annotation 2020-05-09 012633](https://user-images.githubusercontent.com/21369699/81444071-29299600-9194-11ea-9e21-28e87b76bb55.png)
Getting this error with the latest build of mpv.net(5.4.7.0
And no thumbnail being generated.
any fixes ?

**Comment by occivink** [comment]
It might be an mpv.net quirk. Does it work with "regular" mpv?
