### ISSUE TITLE
Re-entering the gallery triggers autoload.lua

### ISSUE THREAD

**Issue by AeliusSaionji** [occivink/mpv-gallery-view#3]
For every time I open the gallery, autoload.lua re-adds every image to the playlist, again. Duplicates quickly pile up in normal use.

I am under Windows, can't test under linux right now.

**Comment by occivink** [comment]
Right, this is a bit tricky. 

The reason why this happens is that to enter "gallery mode" we clear the playlist and save its state. When no file is being played, mpv enters "idle mode" (see `mpv --idle --force-window`) which is just the blank background on which we can draw the thumbnails. Then, when we leave the gallery, the script tries to restore the state of the playlist as it used to be, which triggers `autoload.lua`

Generally it doesn't seem to be a performance concern, but it causes issues such as with autoload or drag&drop. I see multiple solutions, from cleanest to least:

* Ask nicely for a way to enter "idle mode" even with an active playlist
* Switch the currently playing file to a 1x1 transparent image while keeping the active playlist
* Load the playlist at once to avoid autoload being triggered
* Don't touch the playlist at all and keep the active file, but overlay a background manually

**Comment by occivink** [comment]
This should now be fixed, instead of entering idle mode we now simply pause and set the video track to none while the gallery is open, and so we don't need to mess with the playlist anymore.
