### ISSUE TITLE
Folder gallery on file open with mpv

### ISSUE THREAD

**Issue by DmitryMake** [occivink/mpv-gallery-view#31]
Hello! Can I get full directory on single file open? If I open use:
`mpv foo.png`
I get only this single foo.png file in my gallery. So I need to open with:
`mpv *`
How can I automatically scan dir on single file opened?
Thanks!

**Comment by occivink** [comment]
Hello, 
This is best done by using the [autoload.lua] script in the mpv repository, it will load adjacent files in a directory. 
This should all work as expected with the gallery script.
