### ISSUE TITLE
Thumbnail path in portable mpv Windows

### ISSUE THREAD

**Issue by JimPancakes** [occivink/mpv-gallery-view#49]
I am using mpv with "portable_config" folder in it. All scripts load fine but I just don't know how to set the thumbnail path in this case. I made a "gallery-thumbs-dir" folder in "portable_config" but it doesn't work. Putting the direct path to "gallery-thumbs-dir" in playlist_view.conf does work but that is not the solution I'm looking for because if I move mpv someplace else I have to do this all over again thus making it not so portable anymore.

**Comment by JimPancakes** [comment]
Managed to solve it on my own. Thanks for the hint!

**Comment by occivink** [comment]
Could you share your solution?

**Comment by JimPancakes** [comment]
I made changes so that the script would automatically work for both mpv in portable mode on windows and for mpv-android since this is what I wanted to use it for. I don't know if it works on linux or the normal mpv mode on windows.

The changes I made are as follows:

```lua
thumbs_dir = ON_WINDOWS and "%APPDATA%\\mpv\\gallery-thumbs-dir" or "~/.cache/thumbnails/mpv-gallery/",
```
to
```lua
thumbs_dir = mp.command_native({ "expand-path", "~~/thumbnails" }),
```

and

```lua
if ON_WINDOWS then
	thumbs_dir = string.gsub(opts.thumbs_dir, "^%%APPDATA%%", os.getenv("APPDATA") or "%APPDATA%")
else
	thumbs_dir = string.gsub(opts.thumbs_dir, "^~", os.getenv("HOME") or "~")
end
local res = utils.file_info(thumbs_dir)
if not res or not res.is_dir then
	if opts.mkdir_thumbs then
		local args = ON_WINDOWS and { "mkdir", thumbs_dir } or { "mkdir", "-p", thumbs_dir }
		utils.subprocess({ args = args, playback_only = false })
	else
		msg.error(string.format("Thumbnail directory \"%s\" does not exist", thumbs_dir))
	end
end
```
to
```lua
thumbs_dir = opts.thumbs_dir
local res = utils.file_info(thumbs_dir)
if not res or not res.is_dir then
	if opts.mkdir_thumbs then
		if ON_WINDOWS then
			os.execute("mkdir " .. thumbs_dir:gsub("/", "\\"))
		else
			local args = { "mkdir", "-p", thumbs_dir }
			utils.subprocess({ args = args, playback_only = false })
		end
	else
		msg.error(string.format("Thumbnail directory \"%s\" does not exist", thumbs_dir))
	end
end
```

The use of `expand-path` was the key.
